<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="4" total="5" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-09-21T13:00:29 IST" name="Default suite" finished-at="2022-09-21T13:00:51 IST" duration-ms="21627">
    <groups>
    </groups>
    <test started-at="2022-09-21T13:00:29 IST" name="Default test" finished-at="2022-09-21T13:00:51 IST" duration-ms="21627">
      <class name="TestCases_UI.HBI_LoginPageTest">
        <test-method is-config="true" signature="extentReport()[pri:0, instance:TestCases_UI.HBI_LoginPageTest@4802796d]" started-at="2022-09-21T13:00:29 IST" name="extentReport" finished-at="2022-09-21T13:00:30 IST" duration-ms="149" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- extentReport -->
        <test-method is-config="true" signature="setup()[pri:0, instance:TestCases_UI.HBI_LoginPageTest@4802796d]" started-at="2022-09-21T13:00:30 IST" name="setup" finished-at="2022-09-21T13:00:33 IST" duration-ms="3240" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyloginToHBIforNodalOfficer()[pri:5, instance:TestCases_UI.HBI_LoginPageTest@4802796d]" started-at="2022-09-21T13:00:33 IST" name="verifyloginToHBIforNodalOfficer" finished-at="2022-09-21T13:00:51 IST" duration-ms="17830" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [ Chandra DV] but found [Chandra DV]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [ Chandra DV] but found [Chandra DV]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at TestCases_UI.HBI_LoginPageTest.verifyloginToHBIforNodalOfficer(HBI_LoginPageTest.java:84)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyloginToHBIforNodalOfficer -->
        <test-method is-config="true" signature="exit(org.testng.ITestResult)[pri:0, instance:TestCases_UI.HBI_LoginPageTest@4802796d]" started-at="2022-09-21T13:00:51 IST" name="exit" finished-at="2022-09-21T13:00:51 IST" duration-ms="219" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyloginToHBIforNodalOfficer status=FAILURE method=HBI_LoginPageTest.verifyloginToHBIforNodalOfficer()[pri:5, instance:TestCases_UI.HBI_LoginPageTest@4802796d] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- exit -->
        <test-method is-config="true" signature="endReport()[pri:0, instance:TestCases_UI.HBI_LoginPageTest@4802796d]" started-at="2022-09-21T13:00:51 IST" name="endReport" finished-at="2022-09-21T13:00:51 IST" duration-ms="166" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endReport -->
      </class> <!-- TestCases_UI.HBI_LoginPageTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
